# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biliInteractive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1116, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/images/bilidownloader.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("*{\n"
"    font: 14px \"Microsoft YaHei\";\n"
"}\n"
"/* 主体颜色\n"
".QWidget#centralwidget{\n"
"    background-color: rgb(156, 156, 156);\n"
"    border-radius:20px;\n"
"} */\n"
".QWidget#mainwidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"/* 编辑框样式 */\n"
"QLineEdit{\n"
"    border-radius: 15px;\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    padding-left: 5px;\n"
"    padding-right: 27px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(255, 238, 238);\n"
"}\n"
"\n"
"/* 按钮样式 */\n"
"QPushButton[flat=\"false\"]{\n"
"    background-color: rgb(255, 153, 153);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    font: 15px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 153, 153, 255), stop:1 rgba(255, 136, 136, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(190, 115, 115, 255), stop:1 rgba(255, 153, 153, 255));\n"
"}\n"
"QPushButton#btnclose{\n"
"    background-color: rgb(255, 102, 102);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton#btnclose:pressed{\n"
"    background-color: rgb(200, 80, 80);\n"
"}\n"
"QPushButton#btnmax{\n"
"    background-color: rgb(255, 255, 102);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton#btnmax:pressed{\n"
"    background-color: rgb(195, 195, 78);\n"
"}\n"
"QPushButton#btnmin{\n"
"    background-color: rgb(153, 204, 102);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton#btnmin:pressed{\n"
"    background-color: rgb(126, 168, 83);\n"
"}\n"
"\n"
"/* 进度条样式 */\n"
"QProgressBar{\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    height: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 16px \"Microsoft YaHei\";\n"
"    border-radius:6px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: rgb(255, 204, 153);\n"
"    border-radius:6px;\n"
"}\n"
"\n"
"/* 选择表样式 */\n"
"QListWidget{\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    border-radius:15px;\n"
"    padding: 5px;\n"
"}\n"
"QListWidget::item{\n"
"    border: 1px dashed rgb(255, 204, 153);\n"
"    border-radius: 5px\n"
"}\n"
"QListWidget::item:hover{\n"
"    background-color: rgb(255, 204, 153);\n"
"}\n"
"QListWidget::item:focus{\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"/* 选择框样式 */\n"
"QComboBox{\n"
"    border-radius: 15px;\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"QComboBox:hover{\n"
"    background: rgb(255, 238, 238)\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    selection-background-color: rgb(255, 204, 153)\n"
"}\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  left;\n"
"     width :  28px ;\n"
"     border: none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/combo/images/dd.png);\n"
"}\n"
"QComboBox::down-arrow:hover{\n"
"    image: url(:/combo/images/dd1.png);\n"
"}\n"
"QComboBox::down-arrow:pressed{\n"
"    image: url(:/combo/images/dd2.png);\n"
"}\n"
"\n"
"/* 文本框样式 */\n"
"QPlainTextEdit{\n"
"    border-radius: 15px;\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Title Frame样式 */\n"
"QFrame#title{\n"
"    background-image: url(:/title/images/title.png);\n"
"}\n"
"\n"
"/* 分组框样式 */\n"
"QGroupBox{\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    border-radius: 15px;\n"
"    margin-top: 2ex;\n"
"}\n"
"QGroupBox::title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"/* 组合框样式 */\n"
"/*QCheckBox{}*/\n"
"QFrame#title{\n"
"    border: none\n"
"}\n"
"\n"
"/* 树形框样式 */\n"
"QTreeWidget{\n"
"    border: 2px solid rgb(255, 153, 153);\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"}\n"
"QTreeWidget::item{\n"
"    border: 1px dashed rgb(255, 204, 153);\n"
"    border-radius: 5px\n"
"}\n"
"QTreeWidget::item:hover{\n"
"    background-color: rgb(255, 204, 153);\n"
"}\n"
"")
        self.mainwidget = QtWidgets.QWidget(Form)
        self.mainwidget.setGeometry(QtCore.QRect(30, 30, 1051, 601))
        self.mainwidget.setStyleSheet("")
        self.mainwidget.setObjectName("mainwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.mainwidget)
        self.treeWidget.setGeometry(QtCore.QRect(30, 60, 281, 431))
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.btnmax = QtWidgets.QPushButton(self.mainwidget)
        self.btnmax.setGeometry(QtCore.QRect(980, 20, 16, 16))
        self.btnmax.setText("")
        self.btnmax.setFlat(True)
        self.btnmax.setObjectName("btnmax")
        self.btnmin = QtWidgets.QPushButton(self.mainwidget)
        self.btnmin.setGeometry(QtCore.QRect(950, 20, 16, 16))
        self.btnmin.setText("")
        self.btnmin.setFlat(True)
        self.btnmin.setObjectName("btnmin")
        self.btnclose = QtWidgets.QPushButton(self.mainwidget)
        self.btnclose.setGeometry(QtCore.QRect(1010, 20, 16, 16))
        self.btnclose.setText("")
        self.btnclose.setFlat(True)
        self.btnclose.setObjectName("btnclose")
        self.label = QtWidgets.QLabel(self.mainwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("*{\n"
"    font: 18px \"微软雅黑\";\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.mainwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 540, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.mainwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 500, 281, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.mainwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 540, 131, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.mainwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 50, 691, 521))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 691, 451))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.groupBox)
        self.webEngineView.setEnabled(True)
        self.webEngineView.setGeometry(QtCore.QRect(10, 20, 671, 421))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setZoomFactor(1.0)
        self.webEngineView.setObjectName("webEngineView")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 30, 91, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 91, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 30, 111, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 30, 111, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 30, 111, 31))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        self.btnclose.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "节点选择框"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "节点"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "CID"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "机器人"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("Form", "424242455"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "A选项"))
        self.treeWidget.topLevelItem(0).child(0).setText(1, _translate("Form", "545464555"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "3"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(1, _translate("Form", "321561235"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "B选项"))
        self.treeWidget.topLevelItem(0).child(1).setText(1, _translate("Form", "837545476"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("Form", "alive"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(1, _translate("Form", "985337899"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "互动视频下载"))
        self.pushButton_3.setText(_translate("Form", "取消下载"))
        self.pushButton_2.setText(_translate("Form", "开始下载"))
        self.pushButton_5.setText(_translate("Form", "导出节点JSON"))
        self.groupBox_2.setTitle(_translate("Form", "节点浏览器"))
        self.lineEdit_2.setText(_translate("Form", "420"))
        self.lineEdit.setText(_translate("Form", "670"))
        self.label_3.setText(_translate("Form", "高度"))
        self.pushButton_6.setText(_translate("Form", "调整节点图"))
        self.label_2.setText(_translate("Form", "宽度"))
        self.pushButton_7.setText(_translate("Form", "保存为图片"))
        self.pushButton_4.setText(_translate("Form", "保存为网页"))
from PyQt5 import QtWebEngineWidgets
import images_dl_rc
